routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@done')->name('done');
    Route::get('/pending', 'UserController@pending')->name('pending');
    Route::get('/products', 'UserController@products')->name('products');
    Route::get('/following', 'UserController@following')->name('following');
    Route::get('/followers', 'UserController@followers')->name('followers');
});

Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
    Route::get('/', 'UserController@profileSettings')->name('profile');
    Route::get('/account', 'UserController@accountSettings')->name('account');
    Route::get('/password', 'UserController@passwordSettings')->name('password');
    Route::get('/delete', 'UserController@deleteSettings')->name('delete');
});

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback', 'SocialController@Callback');

Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@done')->name('done');
    Route::get('/pending', 'ProductController@pending')->name('pending');
});

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('/', 'ProductsController@newest')->name('newest');
    Route::get('/launched', 'ProductsController@launched')->name('launched');
    Route::get('/new', 'ProductsController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('/', 'QuestionController@newest')->name('newest');
    Route::get('/unanswered', 'QuestionController@unanswered')->name('unanswered');
    Route::get('/popular', 'QuestionController@popular')->name('popular');
    Route::get('/new', 'QuestionController@new')->name('new')->middleware('auth');
});

// Toggles
Route::get('/adminbar', 'Admin\AdminBarController@toggle')->name('adminbar')->middleware('auth');
Route::get('/darkmode', 'UserController@darkMode')->name('darkmode')->middleware('auth');

Route::get('/task/{id}', 'TaskController@task')->name('task');

Route::get('/patron', 'PatronController@patron')->name('patron');

Route::personalDataExports('personal-data-exports');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Overtrue\LaravelSubscribe\Traits\Subscribable;
use Rennokki\QueryCache\Traits\QueryCacheable;

class Product extends Model
{
    use QueryCacheable, Subscribable;

    protected $cacheFor = 3600;

    protected $fillable = [
        'user_id',
        'name',
        'slug',
        'description',
        'avatar',
        'website',
        'twitter',
        'github',
        'producthunt',
        'launched',
        'launched_at',
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function task()
    {
        return $this->hasMany('App\Task');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Task;

class ProductController extends Controller
{
    public function done($slug)
    {
        $product = Product::where('slug', $slug)->firstOrFail();

        return view('product.done', [
            'product' => $product,
            'type' => 'product.done',
            'done_count' => Task::where([['product_id', $product->id], ['done', true], ['user_id', $product->user->id]])->count(),
            'pending_count' => Task::where([['product_id', $product->id], ['done', false], ['user_id', $product->user->id]])->count(),
        ]);
    }

    public function pending($slug)
    {
        $product = Product::where('slug', $slug)->firstOrFail();

        return view('product.pending', [
            'product' => $product,
            'type' => 'product.pending',
            'done_count' => Task::where([['product_id', $product->id], ['done', true], ['user_id', $product->user->id]])->count(),
            'pending_count' => Task::where([['product_id', $product->id], ['done', false], ['user_id', $product->user->id]])->count(),
        ]);
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

class ProductsController extends Controller
{
    public function newest()
    {
        return view('products.newest', [
            'type' => 'products.newest',
        ]);
    }

    public function launched()
    {
        return view('products.launched', [
            'type' => 'products.launched',
        ]);
    }

    public function new()
    {
        return view('products.new');
    }
}

app/Http/Livewire/Product/LoadMore.php
<?php

namespace App\Http\Livewire\Product;

use App\Task;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $listeners = [
        'taskAdded' => 'render',
    ];

    public $product;
    public $type;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($product, $type, $page = 1, $perPage = 1)
    {
        $this->product = $product;
        $this->type = $type;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $tasks = Task::cacheFor(60 * 60)
                ->where([
                    ['product_id', $this->product->id],
                    ['user_id', $this->product->user->id],
                    ['done', $this->type === 'product.done' ? true : false],
                ])
                ->orderBy('created_at', 'desc')
                ->orderBy('done_at', 'desc')
                ->get()
                ->groupBy(function ($date) {
                    return Carbon::parse($date->done_at)->format('d-M-y');
                });

            return view('livewire.user.tasks', [
                'tasks' => $this->paginate($tasks),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Product/Subscribe.php
<?php

namespace App\Http\Livewire\Product;

use Auth;
use Livewire\Component;

class Subscribe extends Component
{
    public $product;

    public function mount($product)
    {
        $this->product = $product;
    }

    public function subscribeProduct()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('message', 'Your account is flagged!');
            }
            if (Auth::user()->id === $this->product->user->id) {
                return session()->flash('message', 'You can\'t subscribe your own product!');
            } else {
                Auth::user()->toggleSubscribe($this->product);
            }
        } else {
            return session()->flash('message', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.product.subscribe');
    }
}

app/Http/Livewire/Product/Tasks.php
<?php

namespace App\Http\Livewire\Product;

use App\Task;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Tasks extends Component
{
    public $listeners = [
        'taskAdded' => 'render',
        'taskDeleted' => 'render',
        'taskChecked' => 'render',
    ];

    public $product;
    public $type;
    public $page;
    public $perPage;

    public function mount($product, $type, $page, $perPage)
    {
        $this->product = $product;
        $this->type = $type;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        $tasks = Task::cacheFor(60 * 60)
            ->where([
                ['product_id', $this->product->id],
                ['user_id', $this->product->user->id],
                ['done', $this->type === 'product.done' ? true : false],
            ])
            ->orderBy('created_at', 'desc')
            ->orderBy('done_at', 'desc')
            ->get()
            ->groupBy(function ($date) {
                return Carbon::parse($date->done_at)->format('d-M-y');
            });

        return view('livewire.product.tasks', [
            'tasks' => $this->paginate($tasks),
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/Products/LoadMore.php
<?php

namespace App\Http\Livewire\Products;

use App\Product;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $type;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($page, $perPage, $type)
    {
        $this->type = $type;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            if ($this->type === 'products.newest') {
                $products = Product::cacheFor(60 * 60)
                    ->orderBy('created_at', 'desc')
                    ->get()
                    ->groupBy(function ($date) {
                        return Carbon::parse($date->created_at)->format('Y,W');
                    });
            } elseif ($this->type === 'products.launched') {
                $products = Product::cacheFor(60 * 60)
                    ->where('launched', true)
                    ->orderBy('created_at', 'desc')
                    ->get()
                    ->groupBy(function ($date) {
                        return Carbon::parse($date->created_at)->format('Y,W');
                    });
            }

            return view('livewire.products.products', [
                'products' => $this->paginate($products),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/Products/NewProduct.php
<?php

namespace App\Http\Livewire\Products;

use App\Product;
use Auth;
use Carbon\Carbon;
use Livewire\Component;

class NewProduct extends Component
{
    public $name;
    public $slug;
    public $description;
    public $website;
    public $twitter;
    public $github;
    public $producthunt;
    public $launched;

    public function updated($field)
    {
        $this->validateOnly($field, [
            'name' => 'required|profanity',
            'slug' => 'required|profanity|max:20|unique:products|alpha_dash',
            'description' => 'nullable|profanity',
        ],
        [
            'name.profanity' => 'Please check your words!',
            'slug.profanity' => 'Please check your words!',
            'description.profanity' => 'Please check your words!',
        ]);
    }

    public function submit()
    {
        $validatedData = $this->validate([
            'name' => 'required|profanity',
            'slug' => 'required|profanity|max:20|unique:products|alpha_dash',
            'description' => 'nullable|profanity',
        ],
        [
            'name.profanity' => 'Please check your words!',
            'slug.profanity' => 'Please check your words!',
            'description.profanity' => 'Please check your words!',
        ]);

        if (Auth::user()->isFlagged) {
            return session()->flash('error', 'Your account is flagged!');
        }

        $launched = ! $this->launched ? false : true;

        if ($launched) {
            $launched_status = true;
            $launched_at = Carbon::now();
            $updated_at = Carbon::now();
        } else {
            $launched_status = false;
            $launched_at = null;
        }

        $product = Product::create([
            'user_id' =>  Auth::user()->id,
            'name' => $this->name,
            'slug' => $this->slug,
            'avatar' => 'https://github.com/taskord.png',
            'description' => $this->description,
            'website' => $this->website,
            'twitter' => $this->twitter,
            'github' => $this->github,
            'producthunt' => $this->producthunt,
            'launched' => $launched_status,
            'launched_at' => $launched_at,
        ]);

        session()->flash('message', 'Product has been created!');

        return redirect()->route('product.done', ['slug' => $product->slug]);
    }

    public function render()
    {
        return view('livewire.products.new-product');
    }
}

app/Http/Livewire/Products/Products.php
<?php

namespace App\Http\Livewire\Products;

use App\Product;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class Products extends Component
{
    public $type;
    public $page;
    public $perPage;

    public function mount($page, $perPage, $type)
    {
        $this->type = $type;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function render()
    {
        if ($this->type === 'products.newest') {
            $products = Product::cacheFor(60 * 60)
                ->orderBy('created_at', 'desc')
                ->get()
                ->groupBy(function ($date) {
                    return Carbon::parse($date->created_at)->format('Y,W');
                });
        } elseif ($this->type === 'products.launched') {
            $products = Product::cacheFor(60 * 60)
                ->where('launched', true)
                ->orderBy('created_at', 'desc')
                ->get()
                ->groupBy(function ($date) {
                    return Carbon::parse($date->created_at)->format('Y,W');
                });
        }

        return view('livewire.products.products', [
            'products' => $this->paginate($products),
            'page' => $this->page,
        ]);
    }
}

app/Http/Livewire/User/Products.php
<?php

namespace App\Http\Livewire\User;

use App\Product;
use Livewire\Component;

class Products extends Component
{
    public $user_id;
    public $page;
    public $perPage;

    public function mount($user, $page, $perPage)
    {
        $this->user_id = $user->id;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function render()
    {
        $products = Product::cacheFor(60 * 60)
            ->where('user_id', $this->user_id)
            ->paginate(20);

        return view('livewire.user.products', [
            'products' => $products,
        ]);
    }
}

resources/views/product/done.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('product.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if (Auth::check() && Auth::user()->id === $product->user->id && !$product->user->isFlagged)
                        @livewire('create-task')
                    @endif
                    @livewire('product.tasks', [
                        'type' => 'product.done',
                        'product' => $product,
                        'page' => 1,
                        'perPage' => 3
                    ])
                </div>
                @include('product.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/pending.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('product.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if (Auth::check() && Auth::user()->id === $product->user->id && !$product->user->isFlagged)
                        @livewire('create-task')
                    @endif
                    @livewire('product.tasks', [
                        'type' => 'product.pending',
                        'product' => $product,
                        'page' => 1,
                        'perPage' => 3
                    ])
                </div>
                @include('product.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/profile.blade.php
<div class="card">
    <div class="card-body d-flex align-items-center">
        <img class="rounded avatar-120" src="{{ $product->avatar }}"/>
        <div class="ml-4">
            <div class="h5 mb-0">
                {{ $product->name }}
                @if ($product->launched)
                    <a href="{{ route('products.launched') }}" class="ml-2 small" data-toggle="tooltip" data-placement="right" title="Launched">
                        {{Emoji::rocket()}}
                    </a>
                @endif
            </div>
            <div class="text-black-50 mb-2">
                {{ "#" . $product->slug }}
            </div>
            @if (Auth::check() && Auth::user()->id !== $product->user->id)
                @livewire('product.subscribe', [
                    'product' => $product
                ])
            @endif
            <span class="small">
                <span class="font-weight-bold">{{ $product->subscribers->count() }}</span> Subscribers
            </span>
            @if ($product->description)
            <div class="mt-3">
                {{ $product->description }}
            </div>
            @endif
            <div class="mt-2 small">
                @if ($product->website)
                    <a class="mr-3" href="{{ $product->website }}">
                        <i class="fa fa-link mr-1"></i>
                        {{ Helper::removeProtocol($product->website) }}
                    </a>
                @endif
                @if ($product->twitter)
                    <a class="mr-3" href="https://twitter.com/{{ $product->twitter }}">
                        <i class="fa fa-twitter mr-1"></i>
                        {{ $product->twitter }}
                    </a>
                @endif
                @if ($product->producthunt)
                    <a class="mr-3" href="https://producthunt.com/{{ $product->producthunt }}">
                        <i class="fa fa-producthunt mr-1"></i>
                        {{ $product->producthunt }}
                    </a>
                @endif
            </div>
            <div class="small mt-3 text-black-50">
                <span class="mr-3">{{Emoji::calendar()}} Lauched at {{ Carbon::parse($product->launched_at)->format("F Y") }}</span>
            </div>
        </div>
    </div>
    <div class="card-footer text-muted">
        <a class="text-dark font-weight-bold mr-4" href="{{ route('product.done', ['slug' => $product->slug]) }}">
            <span class="@if (Route::currentRouteName() === 'product.done') text-primary @endif">Done</span>
            <span class="small font-weight-normal text-black-50">{{ $done_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('product.pending', ['slug' => $product->slug]) }}">
            <span class="@if (Route::currentRouteName() === 'product.pending') text-primary @endif">Pending</span>
            <span class="small font-weight-normal text-black-50">{{ $pending_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="">
            Updates <span class="small font-weight-normal text-black-50">1000</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="">
            Stats <span class="small font-weight-normal text-black-50">1000</span>
        </a>
    </div>
</div>

resources/views/product/sidebar.blade.php
<div class="col-sm">
    <div class="card mb-4">
        <div class="card-header">
            Creator
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">
                <img class="rounded-circle avatar-30 mt-1 ml-2" src="{{ $product->user->avatar }}" height="50" width="50" />
                <a href="{{ route('user.done', ['username' => $product->user->username]) }}" class="ml-2 mr-2 align-text-top font-weight-bold text-dark">
                    {{ $product->user->firstname ? $product->user->firstname . ' ' . $product->user->lastname : $product->user->username }}
                </a>
            </li>
        </ul>
    </div>
</div>