routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['prefix' => '@{username}', 'as' => 'user.'], function () {
    Route::get('/', 'UserController@done')->name('done');
    Route::get('/pending', 'UserController@pending')->name('pending');
    Route::get('/products', 'UserController@products')->name('products');
    Route::get('/following', 'UserController@following')->name('following');
    Route::get('/followers', 'UserController@followers')->name('followers');
});

Route::group(['prefix' => 'settings', 'as' => 'user.settings.', 'middleware' => ['auth']], function () {
    Route::get('/', 'UserController@profileSettings')->name('profile');
    Route::get('/account', 'UserController@accountSettings')->name('account');
    Route::get('/password', 'UserController@passwordSettings')->name('password');
    Route::get('/delete', 'UserController@deleteSettings')->name('delete');
});

Route::get('login/{provider}', 'SocialController@redirect');
Route::get('login/{provider}/callback', 'SocialController@Callback');

Route::group(['prefix' => 'product/{slug}', 'as' => 'product.'], function () {
    Route::get('/', 'ProductController@done')->name('done');
    Route::get('/pending', 'ProductController@pending')->name('pending');
});

Route::group(['prefix' => 'products', 'as' => 'products.'], function () {
    Route::get('/', 'ProductsController@newest')->name('newest');
    Route::get('/launched', 'ProductsController@launched')->name('launched');
    Route::get('/new', 'ProductsController@new')->name('new')->middleware('auth');
});

Route::group(['prefix' => 'questions', 'as' => 'questions.'], function () {
    Route::get('/', 'QuestionController@newest')->name('newest');
    Route::get('/unanswered', 'QuestionController@unanswered')->name('unanswered');
    Route::get('/popular', 'QuestionController@popular')->name('popular');
    Route::get('/new', 'QuestionController@new')->name('new')->middleware('auth');
});

// Toggles
Route::get('/adminbar', 'Admin\AdminBarController@toggle')->name('adminbar')->middleware('auth');
Route::get('/darkmode', 'UserController@darkMode')->name('darkmode')->middleware('auth');

Route::get('/task/{id}', 'TaskController@task')->name('task');

Route::get('/patron', 'PatronController@patron')->name('patron');

Route::personalDataExports('personal-data-exports');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Answer;
use App\Product;
use App\Question;
use App\Task;
use App\User;
use Auth;

class UserController extends Controller
{
    public function done($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        return view('user.done', [
            'user' => $user,
            'type' => 'user.done',
            'done_count' => Task::where([['user_id', $user->id], ['done', true]])->count(),
            'pending_count' => Task::where([['user_id', $user->id], ['done', false]])->count(),
            'product_count' => Product::where('user_id', $user->id)->count(),
            'question_count' => Question::where('user_id', $user->id)->count(),
            'answer_count' => Answer::where('user_id', $user->id)->count(),
        ]);
    }

    public function pending($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        return view('user.pending', [
            'user' => $user,
            'type' => 'user.pending',
            'done_count' => Task::where([['user_id', $user->id], ['done', true]])->count(),
            'pending_count' => Task::where([['user_id', $user->id], ['done', false]])->count(),
            'product_count' => Product::where('user_id', $user->id)->count(),
            'question_count' => Question::where('user_id', $user->id)->count(),
            'answer_count' => Answer::where('user_id', $user->id)->count(),
        ]);
    }

    public function products($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        return view('user.products', [
            'user' => $user,
            'done_count' => Task::where([['user_id', $user->id], ['done', true]])->count(),
            'pending_count' => Task::where([['user_id', $user->id], ['done', false]])->count(),
            'product_count' => Product::where('user_id', $user->id)->count(),
            'question_count' => Question::where('user_id', $user->id)->count(),
            'answer_count' => Answer::where('user_id', $user->id)->count(),
        ]);
    }

    public function following($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        return view('user.following', [
            'user' => $user,
            'done_count' => Task::where([['user_id', $user->id], ['done', true]])->count(),
            'pending_count' => Task::where([['user_id', $user->id], ['done', false]])->count(),
            'product_count' => Product::where('user_id', $user->id)->count(),
            'question_count' => Question::where('user_id', $user->id)->count(),
            'answer_count' => Answer::where('user_id', $user->id)->count(),
        ]);
    }

    public function followers($username)
    {
        $user = User::where('username', $username)->firstOrFail();

        return view('user.followers', [
            'user' => $user,
            'done_count' => Task::where([['user_id', $user->id], ['done', true]])->count(),
            'pending_count' => Task::where([['user_id', $user->id], ['done', false]])->count(),
            'product_count' => Product::where('user_id', $user->id)->count(),
            'question_count' => Question::where('user_id', $user->id)->count(),
            'answer_count' => Answer::where('user_id', $user->id)->count(),
        ]);
    }

    public function profileSettings()
    {
        $user = Auth::user();

        return view('user.settings.profile', [
            'user' => $user,
        ]);
    }

    public function accountSettings()
    {
        $user = Auth::user();

        return view('user.settings.account', [
            'user' => $user,
        ]);
    }

    public function passwordSettings()
    {
        $user = Auth::user();

        return view('user.settings.password', [
            'user' => $user,
        ]);
    }

    public function deleteSettings()
    {
        $user = Auth::user();

        return view('user.settings.delete', [
            'user' => $user,
        ]);
    }

    public function darkMode()
    {
        $user = Auth::user();
        if (Auth::check()) {
            if ($user->isPatron) {
                if ($user->darkMode) {
                    $user->darkMode = false;
                    $user->save();

                    return 'disabled';
                } else {
                    $user->darkMode = true;
                    $user->save();

                    return 'enabled';
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
}

app/Http/Livewire/User/Follow.php
<?php

namespace App\Http\Livewire\User;

use Auth;
use Livewire\Component;

class Follow extends Component
{
    public $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function followUser()
    {
        if (Auth::check()) {
            if (Auth::user()->isFlagged) {
                return session()->flash('message', 'Your account is flagged!');
            }
            if (Auth::user()->id === $this->user->id) {
                return session()->flash('message', 'You can\'t follow yourself!');
            } else {
                Auth::user()->toggleFollow($this->user);
            }
        } else {
            return session()->flash('message', 'Forbidden!');
        }
    }

    public function render()
    {
        return view('livewire.user.follow');
    }
}

app/Http/Livewire/User/Followers.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Followers extends Component
{
    public $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function render()
    {
        return view('livewire.user.followers');
    }
}

app/Http/Livewire/User/Following.php
<?php

namespace App\Http\Livewire\User;

use Livewire\Component;

class Following extends Component
{
    public $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function render()
    {
        return view('livewire.user.following');
    }
}

app/Http/Livewire/User/LoadMore.php
<?php

namespace App\Http\Livewire\User;

use App\Task;
use Carbon\Carbon;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Pagination\Paginator;
use Illuminate\Support\Collection;
use Livewire\Component;

class LoadMore extends Component
{
    public $listeners = [
        'taskAdded' => 'render',
    ];

    public $user_id;
    public $type;
    public $page;
    public $perPage;
    public $loadMore;

    public function mount($user, $type, $page = 1, $perPage = 1)
    {
        $this->user_id = $user->id;
        $this->type = $type;
        $this->page = $page + 1; //increment the page
        $this->perPage = $perPage;
        $this->loadMore = false; //show the button
    }

    public function paginate($items, $options = [])
    {
        $page = $this->page ?: (Paginator::resolveCurrentPage() ?: 1);
        $items = $items instanceof Collection ? $items : Collection::make($items);

        return new LengthAwarePaginator($items->forPage($page, $this->perPage), $items->count(), $this->perPage, $page, $options);
    }

    public function loadMore()
    {
        $this->loadMore = true;
    }

    public function render()
    {
        if ($this->loadMore) {
            $tasks = Task::cacheFor(60 * 60)
                ->where('user_id', $this->user_id)
                ->where('done', $this->type === 'user.done' ? true : false)
                ->orderBy('done_at', 'desc')
                ->get()
                ->groupBy(function ($date) {
                    return Carbon::parse($date->done_at)->format('d-M-y');
                });

            return view('livewire.user.tasks', [
                'tasks' => $this->paginate($tasks),
            ]);
        } else {
            return view('livewire.load-more');
        }
    }
}

app/Http/Livewire/User/Moderator.php
<?php

namespace App\Http\Livewire\User;

use App\User;
use Auth;
use Livewire\Component;

class Moderator extends Component
{
    public $user;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function enrollBeta()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isBeta = ! $this->user->isBeta;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function enrollStaff()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isStaff = ! $this->user->isStaff;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function enrollDeveloper()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isDeveloper = ! $this->user->isDeveloper;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function flagUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $this->user->isFlagged = ! $this->user->isFlagged;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function enrollPatron()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->isPatron = ! $this->user->isPatron;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function enrollDarkMode()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            $this->user->darkMode = ! $this->user->darkMode;
            $this->user->save();
        } else {
            return false;
        }
    }

    public function deleteUser()
    {
        if (Auth::check() && Auth::user()->isStaff) {
            if ($this->user->id === 1) {
                return false;
            }
            $user = User::find($this->user->id);
            $user->delete();

            return redirect()->route('home');
        } else {
            return false;
        }
    }

    public function render()
    {
        return view('livewire.user.moderator');
    }
}

app/Http/Livewire/User/Products.php
<?php

namespace App\Http\Livewire\User;

use App\Product;
use Livewire\Component;

class Products extends Component
{
    public $user_id;
    public $page;
    public $perPage;

    public function mount($user, $page, $perPage)
    {
        $this->user_id = $user->id;
        $this->page = $page ? $page : 1;
        $this->perPage = $perPage ? $perPage : 1;
    }

    public function render()
    {
        $products = Product::cacheFor(60 * 60)
            ->where('user_id', $this->user_id)
            ->paginate(20);

        return view('livewire.user.products', [
            'products' => $products,
        ]);
    }
}

app/Http/Livewire/User/Settings/Account.php
<?php

namespace App\Http\Livewire\User\Settings;

use Auth;
use Livewire\Component;

class Account extends Component
{
    public $user;
    public $username;
    public $email;

    public function mount($user)
    {
        $this->user = $user;
        $this->username = $user->username;
        $this->email = $user->email;
    }

    public function enrollBeta()
    {
        if (Auth::check() && Auth::user()->id === $this->user->id) {
            $this->user->isBeta = ! $this->user->isBeta;
            $this->user->save();
            if ($this->user->isBeta) {
                session()->flash('message', 'Your are now beta member!');
            } else {
                session()->flash('message', 'Your are no longer a beta member!');
            }
        } else {
            return false;
        }
    }

    public function updateAccount()
    {
        if (Auth::check() && Auth::user()->id === $this->user->id) {
            $this->user->username = $this->username;
            $this->user->email = $this->email;
            $this->user->save();

            return session()->flash('message', 'Your account has been updated!');
        }
    }

    public function render()
    {
        return view('livewire.user.settings.account');
    }
}

app/Http/Livewire/User/Settings/Delete.php
<?php

namespace App\Http\Livewire\User\Settings;

use App\User;
use Auth;
use Livewire\Component;

class Delete extends Component
{
    public $user;
    public $confirming;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function confirmDelete()
    {
        $this->confirming = $this->user->id;
    }

    public function deleteAccount()
    {
        if (Auth::check()) {
            $user = User::find($this->user->id);
            $user->task_praise()->delete();
            $user->tasks()->delete();
            $user->products()->delete();
            $user->delete();

            return redirect()->route('home');
        } else {
            return false;
        }
    }

    public function exportAccount()
    {
        if (Auth::check()) {
        } else {
            return false;
        }
    }

    public function render()
    {
        return view('livewire.user.settings.delete');
    }
}

app/Http/Livewire/User/Settings/Password.php
<?php

namespace App\Http\Livewire\User\Settings;

use Livewire\Component;

class Password extends Component
{
    public $user;
    public $existingPassword;
    public $newPassword;
    public $confirmPassword;

    public function mount($user)
    {
        $this->user = $user;
    }

    public function updateAccount()
    {
        if (Auth::check()) {
            $this->user->username = $this->username;
            $this->user->email = $this->email;
            $this->user->save();

            return session()->flash('message', 'Your account has been updated!');
        }
    }

    public function render()
    {
        return view('livewire.user.settings.password');
    }
}

resources/views/user/done.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if (Auth::check() && Auth::user()->id === $user->id && !$user->isFlagged)
                        @livewire('create-task')
                    @endif
                    @livewire('user.tasks', [
                        'type' => 'user.done',
                        'user' => $user,
                        'page' => 1,
                        'perPage' => 3
                    ])
                </div>
                @include('user.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/followers.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @livewire('user.followers', ['user' => $user])
                </div>
                @include('user.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/following.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @livewire('user.following', ['user' => $user])
                </div>
                @include('user.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/pending.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if (Auth::check() && Auth::user()->id === $user->id && !$user->isFlagged)
                        @livewire('create-task')
                    @endif
                    @livewire('user.tasks', [
                        'type' => 'user.pending',
                        'user' => $user,
                        'page' => 1,
                        'perPage' => 3
                    ])
                </div>
                @include('user.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/products.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @include('user.profile')
    <div class="row justify-content-center mt-4">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    @if (Auth::check() && Auth::user()->id === $user->id)
                        @livewire('create-task')
                    @endif
                    @livewire('user.products', [
                        'user' => $user,
                        'page' => 1,
                        'perPage' => 1
                    ])
                </div>
                @include('user.sidebar')
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/profile.blade.php
<div class="card">
    <div class="row">
        <div class="col-md-7">
            <div class="card-body d-flex align-items-center">
                <img class="rounded-circle avatar-120" src="{{ $user->avatar }}" />
                <div class="ml-4">
                    <div class="h5 mb-0">
                        {{ $user->firstname ? $user->firstname . ' ' . $user->lastname : '' }}
                        @if (Auth::check() && Auth::user()->isStaff && Auth::user()->staffShip)
                            <span class="ml-2 text-secondary small">#{{ $user->id }}</span>
                        @endif
                        @if ($user->isPatron)
                            <a class="ml-2 small" href="{{ route('patron') }}" data-toggle="tooltip" data-placement="right" title="Patron">
                                {{Emoji::handshake()}}
                            </a>
                        @endif
                        @if (Auth::check() && $user->isFollowing(Auth::user()))
                            <span class="ml-2 badge bg-light text-black-50">Follows you</span>
                        @endif
                        @if (Auth::check() && Auth::user()->isStaff && $user->isFlagged)
                            <span class="ml-2 badge bg-danger">Flagged</span>
                        @endif
                    </div>
                    <div class="text-black-50 mb-2">
                        {{ "@" . $user->username }}
                    </div>
                    @if (Auth::check() && Auth::user()->id !== $user->id && !$user->isFlagged)
                        @livewire('user.follow', [
                            'user' => $user
                        ])
                    @endif
                    <span class="small">
                        <a class="text-dark" href="{{ route('user.following', ['username' => $user->username]) }}">
                            <span class="font-weight-bold">{{ $user->followings()->count() }}</span>
                            Following
                        </a>
                        <a class="text-dark" href="{{ route('user.followers', ['username' => $user->username]) }}">
                            <span class="font-weight-bold ml-2">{{ $user->followers()->count() }}</span>
                            {{ $user->followers()->count() <= 1 ? "Follower" : "Followers" }}
                        </a>
                        <span class="font-weight-bold ml-2">{{ $user->task_praise->count() }}</span>
                        {{ $user->task_praise->count() <= 1 ? "Praise" : "Praises" }}
                    </span>
                    @if ($user->bio)
                    <div class="mt-3">
                        {{ $user->bio }}
                    </div>
                    @endif
                    <div class="small mt-3">
                        <span>{{Emoji::calendar()}} Joined {{ Carbon::parse($user->created_at)->format("F Y") }}</span>
                        @if ($user->location)
                        <span class="ml-3">{{Emoji::roundPushpin()}} {{ $user->location }}</span>
                        @endif
                        @if ($user->company)
                        <span class="ml-3">{{Emoji::briefcase()}} {{ $user->company }}</span>
                        @if ($user->isStaff)
                        <span class="badge rounded-pill bg-primary ml-1">Staff</span>
                        @endif
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card-body">
                <div class="h5">Highlights</div>
                <div class="mt-3">
                    <div>
                        <span class="font-weight-bold">{{Emoji::fire()}} {{ $user->getPoints(true) }}</span>
                        {{ $user->getPoints(true) < 2 ? 'Reputation' : 'Reputations' }}
                    </div>
                    @if (Auth::check() && Auth::user()->id === $user->id)
                    <div class="mt-2">
                        <span>{{Emoji::blossom()}} You are a</span>
                        <span class="font-weight-bold">{{ count($user->badges) === 0 ? 'Beginner' : $user->badges->last()->name }}</span>
                    </div>
                    @else
                    <div class="mt-2">
                        <span>{{Emoji::blossom()}} {{ $user->username }} is a</span>
                        <span class="font-weight-bold">{{ count($user->badges) === 0 ? 'Beginner' : $user->badges->last()->name }}</span>
                    </div>
                    @endif
                    @if ($user->isBeta)
                    <div class="mt-2">
                        <span class="font-weight-bold">{{Emoji::testTube()}} Beta Program Member</span>
                    </div>
                    @endif
                    @if ($user->isDeveloper)
                    <div class="mt-2">
                        <span class="font-weight-bold">{{Emoji::checkBoxWithCheck()}} Taskord Code Contributor</span>
                    </div>
                    @endif
                </div>
            </div>  
        </div>
    </div>
    <div class="card-footer text-muted">
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.done', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.done') text-primary @endif">Done</span>
            <span class="small font-weight-normal text-black-50">{{ $done_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.pending', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.pending') text-primary @endif">Pending</span>
            <span class="small font-weight-normal text-black-50">{{ $pending_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="{{ route('user.products', ['username' => $user->username]) }}">
            <span class="@if (Route::currentRouteName() === 'user.products') text-primary @endif">Products</span>
            <span class="small font-weight-normal text-black-50">{{ $product_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="">
            Questions <span class="small font-weight-normal text-black-50">{{ $question_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="">
            Answers <span class="small font-weight-normal text-black-50">{{ $answer_count }}</span>
        </a>
        <a class="text-dark font-weight-bold mr-4" href="">
            Stats
        </a>
    </div>
</div>

resources/views/user/sidebar.blade.php
<div class="col-sm">
    @if (Auth::check() && Auth::user()->isStaff && Auth::user()->staffShip)
        @livewire('user.moderator', [
            'user' => $user
        ])
    @endif
    @if ($user->website or $user->twitter or $user->twitch or $user->telegram or $user->github or $user->youtube)
    <div class="card mb-4">
        <div class="card-header">
            Social
        </div>
        <ul class="list-group list-group-flush">
            @if ($user->website)
            <li class="list-group-item">
                <a class="text-dark" href="{{ $user->website }}">
                    <i class="fa fa-link mr-1"></i>
                    {{ Helper::removeProtocol($user->website) }}
                </a>
            </li>
            @endif
            @if ($user->twitter)
            <li class="list-group-item">
                <a class="text-dark" href="https://twitter.com/{{ $user->twitter }}">
                    <i class="fa fa-twitter mr-1"></i>
                    {{ $user->twitter }}
                </a>
            </li>
            @endif
            @if ($user->twitch)
            <li class="list-group-item">
                <a class="text-dark" href="https://twitch.tv/{{ $user->twitch }}">
                    <i class="fa fa-twitch mr-1"></i>
                    {{ $user->twitch }}
                </a>
            </li>
            @endif
            @if ($user->telegram)
            <li class="list-group-item">
                <a class="text-dark" href="https://t.me/{{ $user->telegram }}">
                    <i class="fa fa-telegram mr-1"></i>
                    {{ $user->telegram }}
                </a>
            </li>
            @endif
            @if ($user->github)
            <li class="list-group-item">
                <a class="text-dark" href="https://github.com/{{ $user->github }}">
                    @if (Auth::user()->darkMode)
                    <i class="fa fa-github text-white mr-1"></i>
                    @else
                    <i class="fa fa-github mr-1"></i>
                    @endif
                    {{ $user->github }}
                </a>
            </li>
            @endif
            @if ($user->youtube)
            <li class="list-group-item">
                <a class="text-dark" href="https://youtube.com/{{ $user->youtube }}">
                    <i class="fa fa-youtube mr-1"></i>
                    {{ $user->youtube }}
                </a>
            </li>
            @endif
        </ul>
    </div>
    @endif
    <div class="card mb-4">
        <div class="card-header">
            Products
        </div>
        <ul class="list-group list-group-flush">
            @if (count($user->products) === 0)
            <div class="card-body text-center">
                <i class="fa fa-3x fa-box-open mb-3 text-primary"></i>
                <div class="h5">
                    No products made!
                </div>
            </div>
            @endif
            @foreach($user->products->take(5) as $product)
            <li class="list-group-item">
                <img class="rounded avatar-30 mt-1 ml-2" src="{{ $product->avatar }}" height="50" width="50" />
                <a href="{{ route('product.done', ['slug' => $product->slug]) }}" class="ml-2 mr-2 align-text-top font-weight-bold text-dark">
                    {{ $product->name }}
                </a>
            </li>
            @endforeach
        </ul>
        @if (count($user->products) > 5)
        <div class="card-footer">
            <a class="font-weight-bold" href="{{ route('user.products', ['username' => $user->username]) }}">
                {{ count($user->products) - 5 }} more Products
            </a>
        </div>
        @endif
    </div>
</div>